import { ICaseConvertor } from "../Interfaces/ICaseConvertor";
import { IClassDescription } from "../Interfaces/IClassDescription";
import { IClassDescriptionV1 } from "../Interfaces/IClassDescriptionV1";
import { ActionFailure } from "../Utils/ActionResult";
import { Logger } from "../Utils/Logger";
import TypescriptDataClassGeneratorV1 from "./TypescriptDataClassGeneratorV1";

var myLogger = console.log;
@Logger.log
export default class TypescriptDataClassGenerator extends TypescriptDataClassGeneratorV1 {
    protected _classSpecification!: IClassDescription;

    public set classDescription(newClassDescription: IClassDescription) {
        this._classSpecification = newClassDescription;
    }

    // Holds a map of functions that generate different type
    // of constructors
    protected _constructorCodeGenerators = new Map<string, () => string>
        (
            [
                ["parameterized", this.generateParameterizedConstructor.bind(this)],
                ["default", this.generateDefaultConstructor.bind(this)]
            ]
        );

    // Generates the data class
    @Logger.call()
    public generate(): any {
        // Holds the auto generated comment for the class
        let autoGeneratedComment = `/**${this.N1}* Auto Generated Abstract Data Class${this.N1}*${this.N1}* Generated on : ${new Date().toString()}${this.N1}*/${this.N1}`;

        // Extract the className
        let className = this._classSpecification.className;
        Logger.info(`Generating code for class : `, [className]);

        // Add the decorators of the code (if any)
        let decorators: string[] = this._classSpecification.decorators ?? [];

        // Holds the class code
        let classCode = "";

        // Add the decorators to the class
        if (decorators.length) {
            Logger.info("Decorators found for class", [className]);

            classCode = decorators.reduce((previousValue, decorator) => previousValue + `${decorator}${this.N1}`,
                "");
        } else
            Logger.warn(`Decorators not found for class : ${className}`);

        // Holds the base classes for this class (if any)
        let baseClasses: string[] = this._classSpecification.extends ?? [];
        let extendsClasses = "";

        // Add the base classes to the class
        if (baseClasses.length) {
            Logger.info("Base classes found for class", [className]);

            extendsClasses = baseClasses.reduce(
                (previousValue, baseClass, currentIndex) => previousValue + `${baseClass}${currentIndex != baseClasses.length - 1 ? ", " : " "}`
                , "");
        }
        else
            Logger.warn(`Base classes not found for class : ${className}`);

        // Start adding the code for the class
        classCode += `export abstract class ${className}Abstract ${extendsClasses.length ? "extends " + extendsClasses : ""}{${this.N1}`;

        // Holds code for all the fields
        const fieldList: string[] = [];

        // Holds getter setter code for the fields
        const getterSetterCode: string[] = [];

        // Holds the fields of the class
        const fields = this._classSpecification.fields;
        fields ? Logger.info("Fields found for class", [className]) : Logger.warn(`Fields not found for class : ${className}`);

        // Holds the constructors types that have to be generated for this class
        const constructorTypes = this._classSpecification.constructors;

        if (constructorTypes?.size >= 1) {
            // Get the constructor type from the configuration
            let constructorType = this._classSpecification?.constructors?.keys()?.next().value;

            // TypeScript allows just ONE constructor in the class
            // If there are multiple defined in the config, log appropriate info and warning
            if (constructorTypes?.size == 1) {
                Logger.info(`Generating constructor type ${constructorType} for class`, [className]);
            } else {
                Logger.warn(`Multiple constructors found for class : ${className}`);
                Logger.warn(`Generating the first constructor type : ${constructorTypes?.keys()?.next().value}`);
            }

            // If the constructor type is valid, generate code
            if (this._constructorCodeGenerators.has(constructorType)) {

                // Get the generator for this constructor
                const constructorCodeGenerator = this._constructorCodeGenerators.get(constructorType) ?? (() => "");

                // Invoke the constructor
                let constructorCode = constructorCodeGenerator();

                // Add the constructor code to the class code
                classCode += constructorCode;
            } else {
                // Warn the user about unrecognized constructor type
                Logger.error(`Constructor type not recognized`, [constructorType]);
            }
        }
        else
            Logger.warn(`No constructors to be generated for class : ${className}`);

        // Add fields to the class
        for (const fieldNameKey of fields?.keys()) {
            // Generate the getter and setter for this field
            getterSetterCode.push(this.generateGetter(fieldNameKey));
            getterSetterCode.push(this.generateSetter(fieldNameKey));
        }

        fieldList.forEach(fieldCode => classCode += (fieldCode + `${this.N1}`));
        getterSetterCode.forEach(getterSetter => classCode += (getterSetter + `${this.N1}`));

        return classCode + `${this.N1}}`;
    }

    // Generates default constructor
    @Logger.call()
    public generateDefaultConstructor(): string {
        let constructorCode = `${this.N1 + this.T1}public constructor() { }${this.N1}`;

        return constructorCode;
    }

    // Generates positional (parameterized) constructor
    @Logger.call()
    public generateParameterizedConstructor(): string {
        myLogger("HERE");
        // Holds the fields of this class
        const fields = this._classSpecification.fields;

        // Holds the constructor code
        let constructorCode = `${this.N1 + this.T1}public constructor (${this.N1}`;
        let fieldCount = 0;

        // Go over each field
        for (const fieldName of fields.keys()) {
            fieldCount++;

            // Holds the fieldProperties for this field
            const fieldProperties: Map<string, any> = fields.get(fieldName);

            // Holds the modifier of this field
            const modifier: string = fieldProperties.get("modifier") ?? "public";

            // Holds the data type of this field
            const dataType: string = fieldProperties.get("type") ?? "";

            // Holds the default value of this field
            const defaultValue: string = fieldProperties.get("defaultValue");

            // Holds the comment for this field
            const comment: string = fieldProperties.get("comment") ?? "";

            // Holds the decorators of this field
            const decorators: string[] = fieldProperties.get("decorators") ?? [];

            if (fieldCount == 1)
                constructorCode += `${this.T2 + comment + this.N1}`;

            constructorCode += `${this.T2}${modifier} ${modifier == "public" ? "" : "_"}${fieldName}: ${dataType}${defaultValue ? " = " + defaultValue : ""}`;

            if (fieldCount != fields.size)
                constructorCode += `,${this.N1}`;

            constructorCode += `${this.N1}`;
        }

        // Complete the constructor code
        constructorCode += `${this.T1}) { }${this.N1}`;

        return constructorCode;

    }

    // Generates the getter for the field
    public generateGetter(fieldName: string): string {
        let getterCode = "";

        // Get the properties for this field
        let fieldProperties: Map<string, any> = this._classSpecification.fields.get(fieldName);
        // Get the type of the field
        let dataType: string = fieldProperties.get("type") ?? "any";

        // Get the getter property map for this field
        let getterPropertyMap: Map<string, any> = fieldProperties.get("getter");
        myLogger(`Getter for ${fieldName}`, getterPropertyMap);

        // Return if there is no map found
        if (!getterPropertyMap)
            return getterCode;

        // If there is a getter property map, get the decorators
        let decorators: string[] = getterPropertyMap?.get("decorators");

        // Add the decorators to the getterCode
        getterCode = decorators.reduce((previousValue, decorator) => previousValue + `${this.T1}${decorator}${this.N1}`, "");

        getterCode += `${this.T1}public abstract get ${fieldName}(): ${dataType};${this.N1}`;

        return getterCode;
    }

    // Generates the setter code for the field
    public generateSetter(fieldName: string): string {
        let setterCode = "";

        // Get the properties for this field
        let fieldProperties: Map<string, any> = this._classSpecification.fields.get(fieldName);

        // Get the type of this field
        let dataType: string = fieldProperties.get("type") ?? "any";

        // Get the setter property map for this field
        let setterPropertyMap: Map<string, any> = fieldProperties.get("setter");
        myLogger(`Setter for ${fieldName}`, setterPropertyMap);

        // If there is no setter map, return
        if (!setterPropertyMap)
            return setterCode;

        // Get the decorators for this setter
        let decorators: string[] = setterPropertyMap?.get("decorators") ?? [];

        setterCode = decorators.reduce((previousValue, decorator) => previousValue + `${this.T1}${decorator}${this.N1}`, "");

        setterCode += `${this.T1}public abstract set ${fieldName}(newValue): ${dataType};${this.N1}`;

        return setterCode;
    }

    // Generates field code 
    public generateFieldCode(fieldName: string): string {
        let fieldCode = "";

        // Properties of this field
        let fieldProperties: Map<string, any> = this._classSpecification.fields.get(fieldName);

        // Data type of this field
        let dataType: string = fieldProperties.get("type") ?? "any";

        // Comment for this field
        let comment: string = fieldProperties.get("comment");

        // Holds the decorators for this field
        let decorators: string[] = fieldProperties.get("decorators") ?? [];

        // Modifier for this field
        let modifier: string = fieldProperties.get("modifier") ?? "public";

        // Default value for this field
        let defaultValue: string = fieldProperties.get("defaultValue");

        // Start adding code to the field
        fieldCode += `${this.N1 + this.T1}${comment ? "// " + comment : ""}${this.N1}`;

        // Add decorators to the code
        fieldCode += decorators.reduce((previousValue, decorator) => previousValue + `${this.T1}${decorator}${this.N1}`, "");

        fieldCode += `${this.T1}${modifier} ${modifier == "public" ? fieldName : "_" + fieldName}: ${dataType}${defaultValue ? " = " + defaultValue : ""}`;

        return fieldCode;
    }
}

let mine = new Map<string, any>([["mine", 1], ["yours", 2]]);

console.log(mine.has("his"));
